# Generated by Django 2.2.2 on 2019-07-11 17:20

from django.db import migrations, models
import infra.apps.catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=20, unique=True)),
                ('format', models.CharField(max_length=4)),
                ('file', models.FileField(blank=True, null=True, storage=infra.apps.catalog.models.CustomCatalogStorage(), upload_to=infra.apps.catalog.models.catalog_file_path)),
            ],
        ),
    ]
