# Generated by Django 2.2.2 on 2019-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='format',
            field=models.CharField(choices=[('json', 'JSON'), ('xlsx', 'XLSX')], max_length=4),
        ),
    ]
