# Generated by Django 2.2.2 on 2019-07-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogupload',
            name='identifier',
        ),
        migrations.AddField(
            model_name='catalogupload',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Node'),
            preserve_default=False,
        ),
    ]
