# Generated by Django 2.2.2 on 2019-07-19 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190718_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
