# Generated by Django 2.2.2 on 2019-07-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_catalogupload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogupload',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Node', unique_for_date='uploaded_at'),
        ),
    ]
