# Generated by Django 2.2.2 on 2019-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190722_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogupload',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
