# Generated by Django 2.2.2 on 2019-07-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190722_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogupload',
            unique_together={('node', 'uploaded_at')},
        ),
    ]
