# Generated by Django 2.2.2 on 2019-07-23 14:22

from django.db import migrations, models
import django.db.models.deletion
import infra.apps.catalog.models.distribution
import infra.apps.catalog.storage.distribution_storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190722_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('dataset_identifier', models.CharField(max_length=64)),
                ('identifier', models.CharField(max_length=64)),
                ('file', models.FileField(storage=infra.apps.catalog.storage.distribution_storage.DistributionStorage(), upload_to=infra.apps.catalog.models.distribution.distribution_file_path)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Node', unique_for_date='uploaded_at')),
            ],
        ),
    ]
