# Generated by Django 2.2.2 on 2019-07-25 17:43

from django.db import migrations, models
import infra.apps.catalog.models.distribution
import infra.apps.catalog.storage.distribution_storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='file',
            field=models.FileField(max_length=1000, storage=infra.apps.catalog.storage.distribution_storage.DistributionStorage(), upload_to=infra.apps.catalog.models.distribution.distribution_file_path),
        ),
    ]
