# Generated by Django 2.2.2 on 2019-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190725_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='file_name',
            field=models.CharField(default='latest.data', max_length=800),
            preserve_default=False,
        ),
    ]
