# Generated by Django 2.2.2 on 2019-07-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_distribution_file_name'),
        ('catalog', '0013_node_admins'),
    ]

    operations = [
    ]
