# Generated by Django 2.2.2 on 2019-08-15 19:01

from django.db import migrations, models
import infra.apps.catalog.models.catalog_upload
import infra.apps.catalog.storage.catalog_storage


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_merge_20190730_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogupload',
            name='file',
        ),
        migrations.AddField(
            model_name='catalogupload',
            name='json_file',
            field=models.FileField(blank=True, null=True, storage=infra.apps.catalog.storage.catalog_storage.CustomJsonCatalogStorage(), upload_to=infra.apps.catalog.models.catalog_upload.json_catalog_file_path),
        ),
        migrations.AddField(
            model_name='catalogupload',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, storage=infra.apps.catalog.storage.catalog_storage.CustomExcelCatalogStorage(), upload_to=infra.apps.catalog.models.catalog_upload.xlsx_catalog_file_path),
        ),
    ]
