# Generated by Django 2.2.2 on 2019-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190815_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distribution',
            new_name='DistributionUpload',
        ),
    ]
