# Generated by Django 2.2.2 on 2019-11-07 16:27

from django.db import migrations, models


def create_distribution_models(apps, schema_editor):
    """Normalización del modelo Distribution en dos: Distribution (con los campos 'estáticos')
    y DistributionUpload con el archivo y fecha de subida en cuestión
    """
    DistributionUpload = apps.get_model("catalog", "DistributionUpload")
    Distribution = apps.get_model("catalog", "Distribution")

    for upload in DistributionUpload.objects.all():
        dist, _ = Distribution.objects.get_or_create(identifier=upload.identifier,
                                                     dataset_identifier=upload.dataset_identifier,
                                                     file_name=upload.file_name,
                                                     catalog=upload.node)
        upload.distribution = dist
        upload.save()


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0016_auto_20191107_1616'),
    ]

    operations = [
        migrations.RunPython(create_distribution_models),
    ]
