# Generated by Django 2.2.2 on 2019-11-07 16:27

from django.db import migrations



class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0017_auto_20191107_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionupload',
            name='dataset_identifier',
        ),
        migrations.RemoveField(
            model_name='distributionupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='distributionupload',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='distributionupload',
            name='node',
        ),
    ]
