# Generated by Django 2.2.2 on 2019-11-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_delete_old_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionupload',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Distribution'),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('identifier', 'catalog')},
        ),
    ]
