sudo: required
dist: xenial

services:
- docker

language: python
python:
- "3.7"

env:
- DJANGO_SETTINGS_MODULE=conf.settings.testing

before_install:
- docker-compose build
- docker-compose up -d
- pip install -r requirements/testing.txt

install:
- nvm install v10.16.0
- nvm use v10.16.0
- npm install

script:
- scripts/jscpd.sh
- scripts/tests.sh
- scripts/pylint.sh
- scripts/flake8.sh
